config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users
  resources :shops
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'shops#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
	belongs_to :user
	has_many :books
	accepts_nested_attributes_for :books, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :shops
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
def index
end

def about
end	

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :author_name, :price, :shop_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /shops or /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1 or /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    #@shop = Shop.new
    @shop = current_user.shops.build
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    #@shop = Shop.new(shop_params)
    @shop = current_user.shops.build(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: "Shop was successfully created." }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: "Shop was successfully updated." }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @shop = current_user.shops.find_by(id: params[:id])
    redirect_to shops_path, notice: "Not Authorized For This Action" if @shop.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:shop_name, :location, :email, :phone, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <% form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Book Name" %>
  </div>

  <div class="field mb-3">
    <% form.label :author_name %>
    <%= form.text_field :author_name, class:"form-control", placeholder:"Author Name" %>
  </div>

  <div class="field mb-3">
    <% form.label :price %>
    <%= form.text_field :price, class:"form-control", placeholder:"Price" %>
  </div>

  <div class="field mb-3">
    <% form.label :price %>
    <%= form.text_field :shop_id, class:"form-control", placeholder:"Shop Id" %>
  </div>

    <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Shop</h1>
<br/>
<%= render 'form', book: @book %>
<br/>
<%= link_to 'Show', @book, class:"btn btn-secondary" %>
<%= link_to 'Delete', @book, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> 
<%= link_to 'Back', books_path, class:"btn btn-dark" %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table class="table table-striped table=hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Author name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author_name %></td>
        <td><%= book.price %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Shop', new_book_path, class:"btn btn-secondary" %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path, class:"btn btn-light" %>

app/views/books/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @book.name %>-</h1>
  <p class="lead"><%= @book.author_name %> | <%= @book.price %></p>
  <br/>
  <%= link_to 'Edit', edit_book_path(@book), class:"btn btn-dark" %>
  <%= link_to 'Delete', @book, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> 
<%= link_to 'Back', books_path, class:"btn btn-secondary" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Store', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to "About Us",home_about_path,class:"nav-link" %>
          
        </li>



        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Add Shop",new_shop_path,class:"nav-link" %>
            
          </li>
          
          <li class="nav-item">
            <%= link_to "Sign Out",destroy_user_session_path,method: :delete, class:"nav-link" %>
            
          </li>
          
          <li class="nav-item">
            <%= link_to "Edit Profile",edit_user_registration_path,class:"nav-link" %>
            
          </li>

                    <li class="nav-item">
            <%= link_to "Add Book",new_book_path,class:"nav-link" %>
            
          </li>

          <li class="nav-item">
            <%= link_to "Show Book",books_path,class:"nav-link" %>
            
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to "Sign Up",new_user_registration_path,class:"nav-link" %>
            
          </li>

          <li class="nav-item">
            <%= link_to "Sign In",new_user_session_path,class:"nav-link" %>
            
          </li>



         

        <% end %>

        

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About Us...</h1>

app/views/home/index.html.erb
<h1>Hi</h1>
Let's start building

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Store</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

    <%= render 'home/header' %>
    <div class='container'>
      <br/>
      <% if notice %>
      <%= render 'layouts/alerts'%>
      <% end %>

      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/shops/_form.html.erb
<%= form_with(model: shop) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <% form.label :shop_name %>
    <%= form.text_field :shop_name, class:"form-control", placeholder:"Shop Name" %>
  </div>

  <div class="field mb-3">
    <% form.label :location %>
    <%= form.text_field :location, class:"form-control", placeholder:"Location" %>
  </div>

  <div class="field mb-3">
    <% form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field" mb-3>
    <% form.label :phone %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field mb-3">
    <% form.label :user_id %>
    <%= form.number_field :user_id,id: :shop_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>
<br/>
<%= render 'form', shop: @shop %>
<br/>
<%= link_to 'Show', @shop, class:"btn btn-secondary" %>
<%= link_to 'Delete', @shop, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> 
<%= link_to 'Back', shops_path, class:"btn btn-dark" %>

app/views/shops/index.html.erb
<% if user_signed_in? %>

<h1>Shops List</h1>

<table class="table table-striped table-hover table_bordered">
  <thead class="table-dark">
    <tr>
      <th>Shop name</th>
      <th>Location</th>
      <th>Email</th>
      <th>Phone</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <% if shop.user == current_user %>
      <tr>
        <td><%= link_to shop.shop_name, shop %></td>
        <td><%= shop.location %></td>
        <td><%= shop.email %></td>
        <td><%= shop.phone %></td>
      
        <td><%= link_to 'Delete', shop, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path, class:"btn btn-secondary" %>

<% else %>
<h1>Hi</h1>
Welcome to the app

<% end %>

app/views/shops/new.html.erb
<h1> Add New Shop</h1>
<br/>
<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path, class:"btn btn-light" %>

app/views/shops/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @shop.shop_name %>-</h1>
  <p class="lead"><%= @shop.location %> | <%= @shop.email %> | <%= @shop.phone %>  </p>
  <br/>
  <%= link_to 'Edit', edit_shop_path(@shop), class:"btn btn-dark" %>
  <%= link_to 'Delete', @shop, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> 
<%= link_to 'Back', shops_path, class:"btn btn-secondary" %>
</div>